"""empty message

Revision ID: ba96a64592d3
Revises: e678d39cd862
Create Date: 2023-05-01 11:15:23.990916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba96a64592d3'
down_revision = 'e678d39cd862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=50), nullable=False),
    sa.Column('photo_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
